# This is loaded by the shell that is spawned by vim's command line
# as well as the shell that is spawned by vifm's command line

# source functionality for use in vim's :!<command>
# as well as vifm's :!<command>
if [[ $VIMRUNTIME ]]; then
  # get 256color for vim's :terminal command
  TERM=xterm-256color-italic
  # source zsh aliases
  #source $HOME/.oh-my-zsh/custom/Z_aliases.zsh

  # source only the aliases from OMZSH's git plugin
  # this breaks things now
  #source <(grep alias $HOME/.oh-my-zsh/plugins/git/git.plugin.zsh)

  # source zsh functions
  #source $HOME/.oh-my-zsh/custom/myFunctions.zsh

  # source OMZSH's clipboard plugin
  #source $HOME/.oh-my-zsh/lib/clipboard.zsh
fi

# ---Auto generated by printc plugin---
#fpath=($HOME/.oh-my-zsh/custom/plugins/printc $fpath)
#ZSH_CUSTOM=$HOME/.oh-my-zsh/custom
# -------------------------------------
ZSH_CUSTOM=$HOME/.zsh
fpath=($ZSH_CUSTOM/plugins/printc $fpath)
fpath=($ZSH_CUSTOM/plugins/fzf-utils $fpath)
fpath=($ZSH_CUSTOM/lib $fpath)
fpath=($ZSH_CUSTOM/plugins/k $fpath)
fpath=($ZSH_CUSTOM/completions $fpath)
