
#ZDOTDIR="${${(%):-%x}:P:h}"
ZSH_CUSTOM=$HOME/.zsh
ZDOTDIR="$ZSH_CUSTOM/.zwc_dotfiles"

# source functionality for use in vim's :!<command>
# as well as vifm's :!<command>
if [[ $VIMRUNTIME ]]; then
  # get 256color for vim's :terminal command
  TERM=xterm-256color-italic
  COLORTERM=truecolor
  # source zsh aliases
  source $HOME/.zsh/aliases.zsh

  # source zsh functions
  #source $HOME/.zsh/lib_src/lib

  # source only the aliases from OMZSH's git plugin
  # this breaks things now
  #source <(grep alias $HOME/.oh-my-zsh/plugins/git/git.plugin.zsh)
  autoload -Uz cpdir
  autoload -Uz zrecompile

fi

# ---Auto generated by printc plugin---
#fpath=($HOME/.oh-my-zsh/custom/plugins/printc $fpath)
#ZSH_CUSTOM=$HOME/.oh-my-zsh/custom
# -------------------------------------
if type brew &>/dev/null; then
    fpath=($(brew --prefix)/share/zsh/site-functions $fpath)
fi
fpath=($ZSH_CUSTOM/my_plugins/printc $fpath)
fpath=($ZSH_CUSTOM/my_plugins/k $fpath)
fpath=($ZSH_CUSTOM/lib $fpath)
fpath=($ZSH_CUSTOM/completions $fpath)
fpath=($ZSH_CUSTOM/.zwc_dotfiles $fpath)
