
#ZDOTDIR="${${(%):-%x}:P:h}"
ZSH_CUSTOM=$HOME/.zsh
ZDOTDIR="$ZSH_CUSTOM/.zwc_dotfiles"

# source functionality for use in vim's :!<command>
# as well as vifm's :!<command>
if [[ $VIMRUNTIME ]]; then
  # get 256color for vim's :terminal command
  TERM=xterm-256color-italic
  # source zsh aliases
  source $HOME/.zsh/aliases.zsh

  # source zsh functions
  source $HOME/.zsh/lib_src/lib

  # source only the aliases from OMZSH's git plugin
  # this breaks things now
  #source <(grep alias $HOME/.oh-my-zsh/plugins/git/git.plugin.zsh)

fi

# ---Auto generated by printc plugin---
#fpath=($HOME/.oh-my-zsh/custom/plugins/printc $fpath)
#ZSH_CUSTOM=$HOME/.oh-my-zsh/custom
# -------------------------------------
fpath=($ZSH_CUSTOM/plugins/printc $fpath)
fpath=($ZSH_CUSTOM/plugins/fzf-utils $fpath)
fpath=($ZSH_CUSTOM/lib $fpath)
fpath=($ZSH_CUSTOM/plugins/k $fpath)
fpath=($ZSH_CUSTOM/completions $fpath)
fpath=($ZSH_CUSTOM/.zwc_dotfiles $fpath)
