#!/bin/zsh

# Removes brew package and all of its dependencies that
# aren't relied on by other brew packages

# If a package is passed in that is itself a dependency
# of some other package(s), an error will be given and
# nothing will be removed.

# Depending on how many packages are installed this could take
# up to a few minutes to run. It cross checks every package
# and dependency to make sure nothing that is needed is removed.

if [ $# -ne "1" ]; then
  printf "%s\n" "usage : $0:t <package_to_remove>" >&2
  exit 1
fi

TO_REMOVE=()
DEPS_OF_DEPS=()

# Get dependencies for all leaf packages except for the package being removed
for package in $(brew leaves); do
  if [ $package != $1 ]; then
    DEPS_OF_OTHERS+=($(brew deps $package))
  fi
done


# Get dependencies for all non-leaf packages (the dependencies of the dependencies)
#for dep in $DEPS_OF_OTHERS; do
  #DEPS_OF_DEPS+=($(brew deps $dep))
#done

#DEPS_OF_OTHERS+=($(echo $DEPS_OF_DEPS))

# Make sure the passed in package is not itself a dependency of some package(s)
# If it is bail
#for dep in $DEPS_OF_OTHERS; do
  #if [ $1 = $dep ]; then
    #printf "\n%s\n" "Cannot remove $1. Other packages depend on it." >&2
    #exit 1
  #fi
#done

# Get dependencies for the package being removed
DEPS_OF_REMOVED=$(brew deps $1)

# Get the dependencies that are only dependencies of the package being removed
# and not dependencies of any other package
TO_REMOVE+=($(comm -23 <(print -lo $DEPS_OF_REMOVED | uniq) <(print -lo $DEPS_OF_OTHERS) | uniq))

# Append the parent package to the array of its uniq dependencies
# Now we have an array with the passed in package, as well as its
# dependencies that are not dependencies of anything else
TO_REMOVE+=($1)

# Present the results and get confirmation
printf "The following will be removed:\n\n"
print -l $TO_REMOVE
echo; echo
print -n 'Proceed [yn] : '; read -q yes_or_no; echo; echo

# If 'y' then proceed to remove the package and its uniq dependencies
if [ $yes_or_no = 'y' ]; then
  for package in $TO_REMOVE; do
    #brew rm --force --ignore-dependencies $package
    echo $package # comment this out and uncomment the above line
  done
else
  # else bail
  print "exiting without removal of $1 and dependencies"
fi

