#!/bin/sh
function help_msg () {
   cat << EOF
usage: ctm [-c] [-u] [-ch] [-w] [-h]
-c  <comment>
-u  <uncomment>
-ch <check>
-w  <watch>
-h <show this msg>
EOF

}

TMUX_CONF='/Users/philthy/.dotfiles/tmux/.tmux.conf.local'
TEMP='/tmp/tmp-tmux-conf'

if [ "$1" == '-c' ]; then # comment lines 21-32
  sed -e '21,32 s/^/#/' $TMUX_CONF > $TEMP && mv -f $TEMP $TMUX_CONF
elif [ "$1" == '-u' ]; then # uncomment lines 21-32
  sed -e '21,32 s/#//' $TMUX_CONF > $TEMP && mv -f $TEMP $TMUX_CONF
elif [ "$1" == '-ch' ]; then # display .tmux.conf.local to screen
  pygmentize -f terminal256 -O style=vim -g -l sh $TMUX_CONF
elif [ "$1" == '-w' ]; then # watch the lines 21-32
  watch -n 0.1 lines 21 32 $TMUX_CONF
elif [ "$1" == '-h' ]; then
  help_msg
else
  help_msg
fi


