#!/bin/zsh
####################################
# fuzzy finder for manpages
# usage: fman <take no parameters> OR fman -p for preview mode
# depends on $HOME/.bin/cman for color output man pages
####################################

function get_manpages() {
  local mandirs=("${(@s/:/)$(manpath)}")
  local allPackages
  for mandir in $mandirs; do
    allPackages+=($mandir/*/*)
  done
  for ((i = 1; i < $#allPackages; i++)); do
    if [[ $allPackages[i] =~ gz$ ]]; then
      allPackages[i]=$allPackages[i]:r
    fi
    print $allPackages[i]:t:r
  done
}

function help_msg() {
  cat << EOF
usage: fman [-p] or [-s] {only one or zero options at a time}
-p <start in preview mode>            {optional}
-s <only show bookmarked manpages>    {optional}

press ctrl-s on a selected file to bookmark
EOF
}

HEADER="Fuzzy Man"
# Command that fzf will execute when enter is pressed on selected file
if [ -e "$HOME/.bin/cman" ] || [ -e "$HOME/bin/cman" ]; then
  CMD_TO_EXECUTE="LESS+='N' MANWIDTH=$(tput cols)% cman"
else
  CMD_TO_EXECUTE="LESS+='N' MANWIDTH=$(tput cols)% man"
fi

# if "-h" or "-p" is given we don't want to run get_manpages so we bypass
# that because it is not needed and is resource intensive.
if [ "$1" != "-h" ] && [ "$1" != "--h" ] && [ "$1" != "--help" ] && [ "$1" != "-s" ]; then
  # There are some duplicates between the directories so sort and filter
  if [ "$1" = '-u' ]; then
    ALL_MANPAGES=$(sort -u <<< "$(get_manpages)")
    echo $ALL_MANPAGES > ~/.config/fman/cache
  else
    ALL_MANPAGES=$(cat ~/.config/fman/cache)
  fi
  # call man with all manpages piped to fzf
  if [ "$1" = "-p" ]; then # start in preview mode
    echo "$ALL_MANPAGES" | \
      fzf -i --reverse --header="$HEADER" \
      --preview="man {}" --preview-window="down:90%" \
      --prompt="man-> " --bind "enter:execute($CMD_TO_EXECUTE {})" \
      --bind "ctrl-s:execute(echo {} >> ~/.saved_manpages)"
  else # start without preview mode
    echo "$ALL_MANPAGES" | \
      fzf -i --reverse --header="$HEADER" \
      --prompt="man " --bind "enter:execute($CMD_TO_EXECUTE {})" \
      --bind "ctrl-s:execute(echo {} >> ~/.saved_manpages)"
  fi
# load up bookmark file if "-s" option is given
elif [ "$1" = '-s' ]; then
    fzf -i --reverse --header="$HEADER {Bookmarks}" < ~/.saved_manpages\
    --preview="man {}" --preview-window="down:90%" \
    --prompt="man-> " --bind "enter:execute($CMD_TO_EXECUTE {})" \
    --bind \
    "ctrl-d:execute(sed '/{}/d' ~/.saved_manpages > \
    ~/.tmp_save && /bin/mv -f ~/.tmp_save ~/.saved_manpages)"
else
  help_msg
fi
