#!/usr/local/bin/zsh

autoload -Uz zrecompile
if [[ $1 == '-h' ]] || [[ $1 == '--h' ]]; then
  cat << EOF
usage: mkf func_name

If func_name exists, open it.
Else create it and open it.
EOF
exit 0
fi

FUNC="$ZSH_CUSTOM/lib/${1}"
TEMPLATE="# $1


# vi: ft=zsh"

# If function does not exists then copy TEMPLATE into it,
# and open it, and run first time compilation after closing.
# If it does exist just open existing function, and recompile
# after closing.
if ! [[ -e $FUNC ]]; then
  echo "$TEMPLATE" > "$FUNC"
  "$EDITOR" "$FUNC" && (cd $FUNC:h && zrecompile -p -U -z $FUNC:t)
else
  "$EDITOR" "$FUNC" && zrecompile
fi
