#!/usr/local/bin/zsh

printf -- '\033[1m\033[38;5;038m%s\033[0m' 'exported PATH variable:'
print '\033[38;5;038m'
print -l ${(s|:|)PATH}
print '\033[0m'
printf -- '\033[1m\033[38;5;214m%s\033[0m' 'exported FPATH variable:'
print '\033[38;5;214m'
print -l ${(s|:|)FPATH}

