#!/usr/local/bin/zsh

# pass in target URL
TARGET=$1

/usr/bin/osascript << EOF
set targetURL to "$TARGET"

tell application "Google Chrome"
  set window_list to every window
  delay 0.9

repeat with the_window in window_list
  reload (tabs of the_window whose URL contains targetURL)
end repeat

end tell
EOF








