#!/usr/bin/osascript

set targetURL to "http://127.0.0.1:5000"


tell application "Google Chrome"
  set window_list to every window
  delay 0.9

  repeat with the_window in window_list
    reload (tabs of the_window whose URL contains targetURL)
  end repeat

end tell



# vi: ft=applescript




