#!/usr/local/bin/zsh

usage() {
cat << HELP_MESSAGE
$(basename $0): vnote [-l] [-n] [number] [filename]

-h or --h      shows this help message

-l             lists all current notes 

-n             prompts for a note name and opens a new note by
               that name

               vnote without any flags takes either a line number
               corresponding to those shown by -l, or a filname 
               for opening the existing note
HELP_MESSAGE
}

openNote() {
  /usr/local/bin/vim -c "Note ${1}"
}

# TODO: make it so vnote -n <filename> works by taking a paramter file name
NOTE_DIR=~/Notes/viNotes
if [[ ((!$# -eq 1)  || ("$1" == '-h') || ( "$1" == '--h' )) ]]; then 
  usage
elif [[ ("$1" == '-l') ]]; then 
  /bin/ls -1 "$NOTE_DIR" | nl
elif [[ ("$1" == '-n') ]]; then 
  echo -ne "Enter new note name: "
  read NEW_NOTE
  openNote "$NEW_NOTE"
elif [[ "$1" =~ ^[0-9]+$ ]]; then 
  NOTE_AT_LINE_NUM=$(/bin/ls -1 "$NOTE_DIR" | sed -n "${1}"p)
  if [[ -z "$NOTE_AT_LINE_NUM" ]]; then 
    echo "$1 is an invalid line number"
  else 
    openNote "$NOTE_AT_LINE_NUM"
  fi
else 
  NOTE_EXISTS=0
  for NOTEFILE in $(/bin/ls ~/Notes/viNotes); do
    if [[ ("$NOTEFILE" == "$1") ]]; then 
      NOTE_EXISTS=1
      break
    fi
  done
  if [[ ("$NOTE_EXISTS" == 1) ]]; then
    openNote "$1"
  else 
    echo "$1 is an invalid file name"
  fi
fi

