#!/usr/local/bin/bash



  #if [ $# != 1 ] || [ "$1" == '-h' ] || [ "$1" == '--h' ]; then 
  #echo "\nShow all notes:"
  #echo "\tUsage: $0 -s\n"
  #echo "View a note:"
  #echo "\tUsage: $0 <Note_Name>\n"
  #elif [ "$1" == '-s' ]; then
  #/bin/ls -1 ~/Notes/viNotes/ | nl
  #else 
  #local NOTEFILE
  #local NOTE_EXISTS=0
  #for NOTEFILE in $(/bin/ls ~/Notes/viNotes); do
  #if [ "$NOTEFILE" == "$1" ]; then 
  #NOTE_EXISTS=1
  #break
  #fi
  #done
  #if [ $NOTE_EXISTS == 1 ]; then 
  #/usr/local/bin/vim -c "Note ${1}"
  #else 
  #echo "$1 is not a valid note name"
  #fi
  #fi
usage() {
  printf "Show all available notes:\n"
  printf "\tUsage: %s -s \n" "$(basename "$0")"
  printf "\nView a note by name:\n"
  printf "\tUsage: %s <Note_Name>\n" "$(basename "$0")"
  printf "\nView a note by number:\n"
  printf "\tUsage: %s <n>\n" "$(basename "$0")"
}

openNote() {
  /usr/local/bin/vim -c "Note ${1}"
}


NOTE_DIR=~/Notes/viNotes
if [ $# != 1 ] || [ "$1" == '-h' ] || [ "$1" == '--h' ]; then 
  usage
elif [ "$1" == '-s' ]; then 
  /bin/ls -1 "$NOTE_DIR" | nl
elif [[ "$1" =~ ^[0-9]+$ ]]; then 
  NOTE_AT_LINE_NUM=$(/bin/ls -1 "$NOTE_DIR" | sed -n "${1}"p)
  if [ -z "$NOTE_AT_LINE_NUM" ]; then 
    echo "$1 is an invalid line number"
  else 
    openNote "$NOTE_AT_LINE_NUM"
  fi
else 
  NOTE_EXISTS=0
  for NOTEFILE in $(/bin/ls ~/Notes/viNotes); do
    if [ "$NOTEFILE" == "$1" ]; then 
      NOTE_EXISTS=1
      break
    fi
  done
  if [ "$NOTE_EXISTS" == 1 ]; then
    openNote "$1"
  else 
    echo "$1 is an invalid file name"
  fi
fi

