alias -g L=' | less'
alias -g B='|bat'
alias -g J='|jq'
alias -g SCH='~/Fall_2020'
alias -g DOW='~/Downloads'
alias -g DOC='~/Documents'
alias -g DES='~/Desktop'
alias -g DEK='~/Desktop'
alias -g ECW='~/eclipse-workspace'
alias -g ICL='~/Library/Mobile\ Documents/com~apple~CloudDocs'
alias -g SOU='~/Source_Code'
alias -g NEX='~/Nextcloud'
alias -g NOT='~/Notes'
alias -g CP='| tr -d "\n" | pbcopy'
alias -g CPL='| pbcopy'
alias -g CV='pbpaste'
alias -g NL=' | nl -b a'
alias -g BIN='~/.bin'
alias -g C=" | awk END'{print NR}'"
alias -g G='| rg --no-filename --color never'
alias -g A='|gawk'
alias -g GN='|rg -v'
alias -g GC='| rg --no-filename --color always'
alias -g F='|fzf'
alias -g DSF='| diff-so-fancy | less --tabs=4 -RFX'
alias -g FB='| sort | fzf --reverse --preview "bat --theme=Monokai\ Extended\ Bright \
  --style=numbers,changes --color always {}" --preview-window="down:95%"'
